import { int, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 * Extend this file with additional tables as your product grows.
 * Columns use camelCase to match both database fields and generated types.
 */
export const users = mysqlTable("users", {
  /**
   * Surrogate primary key. Auto-incremented numeric value managed by the database.
   * Use this for relations between tables.
   */
  id: int("id").autoincrement().primaryKey(),
  /** Manus OAuth identifier (openId) returned from the OAuth callback. Unique per user. */
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

// ─── Pipeline Table ──────────────────────────────────────────────────────────
export const pipeline = mysqlTable("pipeline", {
  id: int("id").autoincrement().primaryKey(),
  address: varchar("address", { length: 255 }).notNull(),
  hamlet: varchar("hamlet", { length: 64 }).notNull(),
  type: varchar("type", { length: 64 }).notNull().default('Listing'),
  status: varchar("status", { length: 64 }).notNull().default('Prospect'),
  askPrice: varchar("askPrice", { length: 32 }).default(''),
  dom: int("dom").default(0),
  notes: text("notes").default(''),
  sortOrder: int("sortOrder").default(0),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type PipelineEntry = typeof pipeline.$inferSelect;
export type InsertPipelineEntry = typeof pipeline.$inferInsert;

// ─── Listings Table (MAPS tab — Sprint 41 DB persistence) ───────────────────
// NOTE: Column names match the existing DB table (camelCase, from prior migration)
export const listings = mysqlTable('listings', {
  id:           int('id').autoincrement().primaryKey(),
  address:      varchar('address', { length: 255 }).notNull(),
  price:        varchar('price', { length: 64 }).notNull().default(''),
  hamlet:       varchar('hamlet', { length: 64 }).notNull().default('East Hampton North'),
  url:          text('url').notNull(),
  imageUrl:     text('imageUrl'),
  beds:         varchar('beds', { length: 16 }),
  baths:        varchar('baths', { length: 16 }),
  sqft:         varchar('sqft', { length: 32 }),
  status:       varchar('status', { length: 32 }).notNull().default('Active'),
  syncedAt:     timestamp('syncedAt').defaultNow().notNull(),
  createdAt:    timestamp('createdAt').defaultNow().notNull(),
  updatedAt:    timestamp('updatedAt').defaultNow().onUpdateNow().notNull(),
});

export type Listing = typeof listings.$inferSelect;
export type InsertListing = typeof listings.$inferInsert;
// ─── Daily Brief Table (Task 7 · Today's Brief surface · Apr 22 2026) ────────
// Stores the AM Bruehl Brief generated by William at 5:55 AM each day.
// One row per calendar date. Frontend reads the most recent row.
export const dailyBrief = mysqlTable('daily_brief', {
  id:           int('id').autoincrement().primaryKey(),
  briefDate:    varchar('brief_date', { length: 16 }).notNull().unique(), // YYYY-MM-DD
  hamptons:     text('hamptons').notNull(),   // ~200w Hamptons market section
  markets:      text('markets').notNull(),    // ~200w Markets section
  art:          text('art').notNull(),        // ~200w Art section
  audioUrl:     text('audio_url'),            // William voice audio URL (optional)
  generatedAt:  timestamp('generated_at').defaultNow().notNull(),
  createdAt:    timestamp('created_at').defaultNow().notNull(),
});
export type DailyBrief = typeof dailyBrief.$inferSelect;
export type InsertDailyBrief = typeof dailyBrief.$inferInsert;
