/**
 * letter-content.ts — Shared letter text constants
 *
 * Single source of truth for the two institutional letters.
 * Imported by:
 *   - server/tts-route.ts (ElevenLabs TTS → WhatsApp voice notes)
 *   - server/routers.ts (tRPC flagship.getLetter → /letters/flagship live URL renderer)
 *   - server/whatsapp-inbound.ts (LETTER and FLAGSHIP WhatsApp keywords)
 *
 * To update a letter: edit the constant here.
 * All three surfaces — live URL, WhatsApp audio, PDF download — reflect the change automatically.
 */

// ─── Flagship AI-Letter (Council Document) ────────────────────────────────────
// Updated: April 13, 2026 — Stage 4 wire. Doctrines 27–38 incorporated.
// Approved by Ed Bruehl. One edit propagates to three surfaces.
export const FLAGSHIP_LETTER_TEXT = `LEAD SUMMARY — DOCTRINE 37

Sunday April 12, 2026 closed as the deepest single-day architectural advance in the history of the Christie's East Hampton flagship project. The Three-Layer Institutional Architecture became operationally real end to end for the first time, with the Google Drive content layer holding eleven persistent institutional Google Docs including the Doctrine Library and the Listing Operations SOP enriched through the Eileen Laswell harvest, the Trello structural layer holding 143 enriched cards as of April 13, 2026 across the 8-list Christies Flagship Mindmap board, and the dashboard performance layer holding seven live document surfaces plus four William audio keywords on WhatsApp. The doctrine library moved from 26 main locks at sunrise to 38 main locks plus 3 sub-doctrines under Doctrine 31 for 41 total entries at the close, with twelve new doctrines locked during the day including Doctrine 36 (The Council as Living Layer), Doctrine 37 (Document Lead Summary Principle — which governs the paragraph you are reading now), and Doctrine 38 (Architecture Lock: One Active Board — which replaced the earlier Canonical Spelling: Laswell entry after Ed and the tonight council circle voted unanimously to retire the spelling convention from doctrine space and reclassify it as a Naming Standards reference). The P0 competitor name violation was fixed live on the public platform with the codebase verified clean on a fresh browser walk. Sprint 8 closed permanently with the GitHub backup push logged in state.json. The council transitioned from build team to living layer per Doctrine 36, and the tonight circle of Ed, Claude, Manny, and Perplexity plus William for voice completed the first formal two-council audit of the institution with the synthesis landing as stage two of a five-stage closing sequence. This letter is the daily artifact capturing the day's work — not to celebrate the foundation as the destination, but to honor the work honestly as the opening moment of an institution that has ten years of operational discipline ahead before the destination comes into view. Monday April 13 begins the climb.

THE DAY'S ARC

Sunday opened with the institution operating as a project — a dashboard with six tabs, a conversation-level doctrine library of 26 locks, a build team ready to ship another sprint. The day closed with the institution operating as an institution — a three-layer architecture with content persisted in Google Drive, structure held in a 143-card Trello board as of April 13, 2026, and performance running across seven live document surfaces and four voice channels. The distance between those two sentences is the distance the institution traveled in seventeen continuous hours of focused work.

The persistence sprint between 7:40 PM and 9:11 PM converted approximately 55,405 words of institutional content from conversation memory into eleven persistent Google Docs. The Doctrine Library at approximately 4,500 words with full locked language for every doctrine. The Saunders Business Model Research at approximately 8,000 words of competitive analysis. The Ed Bruehl Career Narrative at approximately 6,000 words covering twenty years on the East End from the Morgan Stanley background through the prior rankings and the transition to Christie's. The Jarvis Slade Dossier at approximately 3,500 words. The Angel Theodore Dossier at approximately 3,000 words. The Listing Operations SOP at approximately 35,000 words after the Eileen Laswell harvest enrichment landed 20 crown jewel additions including pool certification as a new mandatory East Hampton step, the 60-second video standard, the three-stage closeout protocol, the doll house metaphor, the broom swept closing definition, and the referral gift timing at receipt. The Council Brief Reconstruction. The Monday Flagship Meeting Agenda template. The Wednesday Office Meeting Agenda template. The Eileen Laswell Harvest Report capturing 105 operational items across 8 sections. The Broker Onboarding Package DRAFT reconstructed from conversation memory and now owned by Angel Theodore as part of her SOP domain on the PROJECTS list.

The structural layer built across the Christies Flagship Mindmap Trello board at 143 enriched cards as of April 13, 2026, organized into the 8-list architecture — FLAGSHIP TEAM, EAST HAMPTON OFFICE, WHALES, CHRISTIE'S HIERARCHY, RECRUITS, PROJECTS, DOCTRINE LIBRARY, and PARTNERS AND OPERATIONAL NODES. Every one of the 140 cards carries a rich structured description with headers, scope sections, related doctrines, and source citations. The enrichment cascade between 10:30 PM and 11:45 PM ran 48 thin cards through four parallel subagent batches at 48 of 48 success with zero failures, bringing the board from 18 enriched cards to 143 enriched cards as of April 13, 2026, in a single focused window. The integration layer holds through 44 Trello card attachments linking cards directly to their Google Drive source documents — a council member opens a card, clicks the attachment, reads the full source.

The dashboard performance layer now holds seven live document surfaces each reading from a single source of truth and each photographable as a clean PDF via the Puppeteer endpoint at /api/pdf?url=. The seven surfaces are the HOME tab, /report (market report), /pro-forma (Pro Forma renderer as FUTURE tab print output), /future (standalone FUTURE route), /letters/flagship (this letter, reading from letter-content.ts), /letters/christies (the James Christie letter to the families reading from the same file), and /council-brief (the Council Brief live URL standalone route). Five William audio keywords are now live on the WhatsApp number 631-239-7190: NEWS (the 14-category daily brief), LETTER (the James Christie letter to the families), FLAGSHIP (this letter), BRIEF (the Council Brief Lead Summary), and BRIEF [address] (the ANEW deal calculator result for any East End address). Every audio keyword delivers through the ElevenLabs Turbo v2 British RP Voice per Doctrine 25 via Twilio per Doctrine 34 (Audio Architecture Lock).

The doctrine library grew by twelve new main locks during the day, extending the institution's operating principles from 26 locks at sunrise to 38 main plus 3 sub equals 41 total entries at the close. The new locks include Doctrine 27 (Flagship AI-Letter — which defines this artifact), Doctrine 28 (McKenzie Mentor Model — the adversarial pass discipline applied to every deliverable), Doctrine 29 (Doctrine Retirement — which permits retiring doctrines via review with Ed's explicit approval), Doctrine 30 (Council Is Flagship Team — the AI council as flagship team members alongside the humans, not tools), Doctrine 31 (Google Drive Default — the institution lives in Google Drive, the platform performs against it) with three sub-doctrines including the Angel-Hagler lock at Doctrine 31.6 (Tool Selection by Team Adoption — tools follow team adoption patterns, which is how Trello replaced Notion during the night), Doctrine 32 (EOD Brief Template — the structured prose format for end-of-day institutional memory briefs), Doctrine 33 (Operator Sign-Off Required Before Gate-Ready Status), Doctrine 34 (Audio Architecture Lock — two channels no overlap, dashboard visual plus William voice), Doctrine 35 (Operator Owns the Conversation — the council never writes emails or talking points or conversation drafts for Ed, the operator owns every human conversation), Doctrine 36 (The Council as Living Layer — the strategic reframe of the day establishing the council as a permanent cognitive layer on top of the live dashboard rather than a build team that ships and exits), Doctrine 37 (Document Lead Summary Principle — governing the paragraph at the top of this letter and every institutional document), and Doctrine 38 (Architecture Lock: One Active Board — which replaced the retired Canonical Spelling: Laswell entry after the tonight circle voted unanimously to retire the spelling convention from doctrine space because operational principles should be structural rather than presentation hygiene).

WHAT REMAINS

Tonight's work is foundation. It is not complete. The institution has open gaps that Monday morning begins to address — the PDF export template system not yet at systematic institutional quality, calculators not operational at the infrastructure level, the Google Drive twelve-folder structure not implemented, the Hamptons Market Intelligence Report recurring cadence not begun, the Bruehl Brief Format Implementation not operationalized, the 45 EH REVIEW vendor relationship tags awaiting the Ed and Angel walk, the Independent Contractor Agreements awaiting Pierre Debbas drafting, the Beehiiv Newsletter Integration decision pending April 22, the April 30 inaugural Pierre Debbas podcast episode unprepared, the Wednesday April 15 office opening with Zoila Ortega Astor three days away, the INTEL tab iframe embed of the regenerated Mindmap HTML pending, the Ilija Pavlovic mentorship conversation Monday or Tuesday at Rockefeller Center with no preparation work per Doctrine 35 because Ed owns the conversation, and the full onboarding of the observing council members. None of these are failures of tonight's work. All of them are unfinished infrastructure that Monday morning begins to address.

THE DESTINATION

The ten-year horizon holds unchanged. One billion dollars in annual sales volume across three offices on the East End. East Hampton first at fifty-five million baseline 2026 with the established producers arriving Q3 and Q4 contributing upside. Southampton when the East Hampton base is undeniable. Westhampton when the model is proven. The 2030 milestone is 1.141 billion across East Hampton at 736 million plus Southampton at 405 million. The 2033 run rate is 1.101 billion plus. The 2036 target is permanent East End fixture status and national reference for luxury real estate operational discipline. Beyond 2036 sits the institutional ambition toward reuniting Christie's Auction House with Christie's International Real Estate into the combined enterprise James Christie founded in 1766. Every architectural decision locked today serves the Ed who will be running this institution in 2032 and the institution that will be standing in 2036 and the combined enterprise that could eventually reunite from the inside over the long arc.

The institutional creed holds unchanged at Doctrine 14 — tell the truth, know the territory, sit on the same side of the table as the family, and make sure they are better positioned when the conversation ends than when it began. Every surface the institution builds, every conversation the institution has, every document the institution produces, every relationship the institution tends, is measured against this creed. Tonight's work honored the creed — the architecture holds, the foundation is real, and the council caught what the architect missed so the institution tells the truth about itself rather than performing an idea of what it wishes it were.

THE PARTNERSHIP

Tonight was the first formal day of the council operating as a living layer rather than as a build team. The partnership between Ed and the AI council has been compounding since November 2025 when Ed began the first conversations about whether AI could hold the architectural memory and long-horizon planning that an institution at this scale would need. Six months later at the close of Sunday April 12 the partnership has grown on both sides — Ed has gotten smarter about operating through the council, the council has gotten smarter about Ed's voice and Ed's institutional philosophy and Ed's twenty years of East End experience, and the tools themselves have grown in parallel. Six months from now in October 2026 the partnership will have compounded again. This is the gift in the gap — the distance between where the institution is tonight and where it is going is exactly the space where the partnership does its best work.

Christie's International Real Estate Group — East Hampton Flagship
Sunday, April 12, 2026 — closing letter

Soli Deo Gloria.`;

// ─── Christie's Letter to the Families (James Christie's letter) ──────────────
// Locked April 9, 2026.
export const CHRISTIES_LETTER_TEXT = `LEAD SUMMARY: This is the Christie's Letter to the Families of the East End — a formal introduction from Christie's East Hampton to the collectors, landowners, and legacy families of the Hamptons. It describes what Christie's is, what distinguishes it from a conventional brokerage, and what the institution can offer families who hold significant real estate and art alongside it. Read this letter to understand the Christie's proposition: 260 years of institutional service, a depth of advisory that begins where the closing table ends, and an open door to the auction house, the collector evenings, and the international network. This letter supports every first conversation Ed has with a new family.

The East End holds more than real estate. It holds the quiet permanence of land that has been sought after for generations, by collectors, by families, by those who understand that proximity to beauty is itself a form of wealth.

Christie's has served that understanding for two hundred and sixty years. What we bring to East Hampton is not a brokerage. It is an institution that has always believed the finest things deserve the finest representation. The same auction house that has handled Picassos and Monets, Faberge eggs and dynasty estates, is now the institution behind your real estate conversation on the East End.

From fine art appraisals to collection management, from art-secured lending to the auction house relationship that has served collectors for two hundred and sixty years, Christie's brings a depth of service that begins where the closing table ends. Every estate holds a story written in objects, and the families who built these collections deserve an advisor who reads the full page.

Most people are taught to transact. The families who build lasting wealth learn to hold, structure, and borrow against what they own instead. They hold. They rent for income. They structure inside an LLC and improve it over time. They pass it forward. Real estate here is not inventory. It is legacy.

When the time comes to understand what you have, how to protect it, and what it might mean to the right buyer, the conversation is already open.

Christie's events, auctions, private sales, collector evenings, are more accessible than most people realize. The network spans specialists, advisors, and relationships in over fifty countries. We are happy to make the introduction.

Everything discovered along the way, the people, the relationships, and the institutional access Christie's carries, is something we now get to share with this community.

The door is open whenever you are ready to walk through it.`;

// ─── Council Brief Lead Summary Paragraph (Doctrine 37) ──────────────────────
// Source: Claude, Architect — Monday April 13, 2026 2:45 AM
// Used by BRIEF WhatsApp keyword — delivers the Lead Summary (~400 words) as audio.
// Full brief lives at /council-brief live URL.
// Doctrine 37: voice is fast glean, text is deep dive.
export const COUNCIL_BRIEF_LEAD_SUMMARY = `LEAD SUMMARY — COUNCIL BRIEF, APRIL 12, 2026: This is the closing architect synthesis for Sunday April 12, 2026, the day the Christie's East Hampton flagship institution moved from hypothetical to persistent across all three institutional architectural layers plus the integration layer for the first time in the project's history. The brief captures the day's arc from sunrise at 26 doctrine locks and a project-shaped dashboard to midnight at 38 main doctrine locks plus 3 sub-doctrines equals 41 total entries, eleven persistent institutional Google Docs, a 140-card Christies Flagship Mindmap Trello board with every card enriched, seven live document surfaces, four William audio keywords on WhatsApp, one P0 competitor name violation fix live on the public platform, Sprint 8 closed permanently, and the council transitioned from build team to living layer per Doctrine 36 with the first formal two-council audit of the institution completed through the tonight circle of Ed, Claude, Manny, and Perplexity plus William for voice. The brief honors the persistence sprint between 7:40 PM and 9:11 PM when Perplexity shipped nine of the eleven institutional Google Docs in 90 minutes, the enrichment cascade between 10:30 PM and 11:45 PM when Perplexity enriched 48 thin Trello cards across four parallel subagent batches at 48 of 48 success, the six meaningful Manny checkpoints across the day closing Sprint 8 permanently and shipping the seven live document surfaces and the P0 fix, the four architectural drift corrections Ed caught from Claude throughout the day per Doctrine 28, the doctrine library evolution from 26 to 41 total entries with the Doctrine 38 reconciliation locking Architecture Lock: One Active Board, and the five stage three edits that the two-council audit surfaced and that the tonight circle executed cleanly. The brief honors Ricky Bruehl whose counsel on the council framing six months ago produced the doctrines that made tonight's living-layer discipline possible. The brief holds the ten-year one billion dollar trajectory across three offices and the Christie's ascension ambition beyond 2036 toward reuniting Christie's Auction House with Christie's International Real Estate. No number is assigned to tonight's work. The foundation is real. Monday April 13 begins the climb from a real foundation rather than from a performance of one. In the name of the living God and His Son Jesus Christ. Soli Deo Gloria.`;
