/**
 * BruehlBriefBulletin.tsx — Midnight Reflective Close
 * INTEL Tab · Section 9 · Bulletin Board
 *
 * Six sections per playbook:
 *   1. Day in Review — market signals and pipeline movement
 *   2. Stalled Deals — DOM > 45 days flagged for attention
 *   3. Tomorrow Edge — first priority, first call, first move
 *   4. Scripture for Rest — KJV/NKJV rotation (day-of-year index)
 *   5. Mentor Line — finance/real estate wisdom rotation
 *   6. Soli Deo Gloria close
 *
 * Auto-generated by refresh_bruehl_brief.py · Thursday, April 16, 2026
 * Issue 211
 */
import React from 'react';
// ─── Tonight's Brief Data ─────────────────────────────────────────────────────
export const BRIEF_DATA = {
  date: 'Thursday, April 16, 2026',
  issueNumber: 211,
  // Section 1 — Day in Review
  dayInReview: {
    headline: 'Markets advance; East Hampton pipeline under active review.',
    marketSignals: [
      { label: 'S&P 500', value: '7,022.95', change: '+55.57', pct: '+0.80%', direction: 'up' },
      { label: '10Y Treasury', value: '4.28%', change: '+0.03', pct: '+0.61%', direction: 'up' },
      { label: '30Y Treasury', value: '4.89%', change: '+0.02', pct: '+0.47%', direction: 'up' },
      { label: 'Gold (GC)', value: '$4,835.20', change: '+11.60', pct: '+0.24%', direction: 'up' },
      { label: 'VIX', value: '18.13', change: '-0.04', pct: '-0.22%', direction: 'down' },
    ],
    pipelineNote: 'Equity markets closed higher. The S&P 500 at 7,022.95 signals continued institutional confidence. Rate environment remains firm — 30-year at 4.89% keeps buyer calculus tight on leveraged transactions above $5M. VIX at 18.13 and declining reflects reduced near-term volatility expectations. Pipeline read: 4 active listings on CIREG. Conditions favor motivated sellers and cash-positioned buyers.',
  },
  // Section 1b — Luxury Real Estate Stocks
  luxuryStocks: [
      { label: 'Zillow (Z)', value: '$43.50', change: '+2.61', pct: '+6.38%', direction: 'up' },
      { label: 'CoStar (CSGP)', value: '$39.31', change: '+1.71', pct: '+4.55%', direction: 'up' },
      { label: 'Compass (COMP)', value: '$7.28', change: '+0.19', pct: '+2.68%', direction: 'up' },
  ],
  // Section 2 — Stalled Deals (DOM > 45 days)
  stalledDeals: {
    note: 'The following active listings have exceeded 45 days on market and require direct attention. Each demands a fresh conversation — pricing posture, marketing refresh, or seller expectation reset.',
    deals: [
            {
        address: '18 Tara Road, Montauk, NY',
        town: 'NY',
        dom: 'Active',
        price: '$3,990,000',
        action: 'Review DOM in Pipeline · Schedule seller call if >45 days · Assess pricing posture',
        priority: 'high',
      },
            {
        address: '140 Hands Creek Road, East Hampton, NY',
        town: 'NY',
        dom: 'Active',
        price: '$3,500,000',
        action: 'Review DOM in Pipeline · Schedule seller call if >45 days · Assess pricing posture',
        priority: 'high',
      },
            {
        address: '3 Sycamore Way, Water Mill, NY',
        town: 'NY',
        dom: 'Active',
        price: '$2,990,000',
        action: 'Review DOM in Pipeline · Schedule seller call if >45 days · Assess pricing posture',
        priority: 'high',
      },
            {
        address: '30 Rampasture Road, Unit R, Hampton Bays, NY',
        town: 'NY',
        dom: 'Active',
        price: '$499,000',
        action: 'Review DOM in Pipeline · Schedule seller call if >45 days · Assess pricing posture',
        priority: 'high',
      },
    ],
    instruction: 'Open the Pipe tab, sort by ERS Signed date, and flag any listing where the signed date is on or before March 2, 2026 (45-day threshold from Thursday, April 16, 2026). Each flagged listing requires a direct seller call before end of week.',
  },
  // Section 3 — Tomorrow Edge
  tomorrowEdge: {
    firstPriority: 'Friday close — confirm all open negotiations have a clear next step. No deal should go into the weekend without a defined follow-up.',
    firstCall: 'Call the most time-sensitive seller in the active pipeline. Lead with market data: S&P at 7,022.95, rates holding. Reinforce that serious buyers are active and positioned.',
    firstMove: 'Review the INTEL Web for any new relationship signals — cross-reference with Trello board for open action items. With 4 active listings on CIREG, identify one new introduction to make before end of week.',
  },
  // Section 4 — Scripture for Rest (NKJV)
  scripture: {
    version: 'NKJV',
    reference: '2 Timothy 1:7',
    text: 'For God has not given us a spirit of fear, but of power and of love and of a sound mind.',
    note: 'Sound mind. Sound strategy. Sound institution.',
  },
  // Section 5 — Mentor Line
  mentorLine: {
    quote: 'The wise young man or wage earner of today invests his money in real estate.',
    attribution: 'Andrew Carnegie',
    context: 'The AnewHomes thesis. The equity architecture. The 300-day arc. All of it begins here.',
  },
  // Section 6 — Soli Deo Gloria
  soliDeoGloria: {
    close: 'The work of Thursday, April 16, 2026 is complete. The pipeline moves. The institution holds. The standard is unchanged.',
    benediction: 'Soli Deo Gloria.',
  },
};
// ─── Styles ───────────────────────────────────────────────────────────────────

const NAVY = '#1B2A4A';
const GOLD = '#C8AC78';
const CREAM = '#FAF8F4';
const MUTED = 'rgba(200,172,120,0.65)';
const DIVIDER = 'rgba(200,172,120,0.2)';

const SERIF: React.CSSProperties = { fontFamily: '"Cormorant Garamond", serif' };
const LABEL: React.CSSProperties = { fontFamily: '"Barlow Condensed", sans-serif' };
const BODY: React.CSSProperties = { fontFamily: '"Source Sans 3", sans-serif' };

// ─── Sub-components ───────────────────────────────────────────────────────────

function SectionLabel({ number, title }: { number: string; title: string }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 14 }}>
      <div style={{
        ...LABEL,
        fontSize: 9,
        letterSpacing: '0.22em',
        textTransform: 'uppercase',
        color: GOLD,
        background: 'rgba(200,172,120,0.1)',
        border: `1px solid ${DIVIDER}`,
        borderRadius: 2,
        padding: '3px 8px',
        whiteSpace: 'nowrap',
      }}>
        {number}
      </div>
      <div style={{
        ...LABEL,
        fontSize: 11,
        letterSpacing: '0.18em',
        textTransform: 'uppercase',
        color: GOLD,
      }}>
        {title}
      </div>
    </div>
  );
}

function MarketSignalRow({ label, value, change, pct, direction }: {
  label: string; value: string; change: string; pct: string; direction: 'up' | 'down' | 'flat';
}) {
  const color = direction === 'up' ? '#5a9e6f' : direction === 'down' ? '#c0392b' : 'rgba(200,172,120,0.7)';
  return (
    <div style={{
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '7px 0',
      borderBottom: `1px solid ${DIVIDER}`,
    }}>
      <div style={{ ...BODY, fontSize: '0.78rem', color: 'rgba(250,248,244,0.75)', minWidth: 140 }}>{label}</div>
      <div style={{ ...BODY, fontSize: '0.82rem', color: CREAM, fontWeight: 600, minWidth: 90, textAlign: 'right' }}>{value}</div>
      <div style={{ ...BODY, fontSize: '0.75rem', color, minWidth: 100, textAlign: 'right' }}>
        {change !== '\u2014' ? `${change} (${pct})` : '\u2014'}
      </div>
    </div>
  );
}

// ─── Main Component ───────────────────────────────────────────────────────────

export default function BruehlBriefBulletin() {
  const d = BRIEF_DATA;

  return (
    <div
      id="intel-layer-9"
      style={{
        background: NAVY,
        borderTop: `1px solid ${DIVIDER}`,
        padding: '0',
      }}
    >
      {/* Header */}
      <div style={{
        background: 'rgba(0,0,0,0.25)',
        borderBottom: `1px solid ${DIVIDER}`,
        padding: '28px 32px 20px',
      }}>
        <div style={{ ...LABEL, fontSize: 9, letterSpacing: '0.28em', textTransform: 'uppercase', color: MUTED, marginBottom: 6 }}>
          Christie\'s East Hampton · Bruehl Brief · Midnight Reflective Close
        </div>
        <div style={{ display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', flexWrap: 'wrap', gap: 8 }}>
          <h3 style={{ ...SERIF, color: CREAM, fontWeight: 400, fontSize: '1.55rem', margin: 0 }}>
            Bulletin Board
          </h3>
          <div style={{ ...LABEL, fontSize: 9, letterSpacing: '0.18em', color: MUTED, textTransform: 'uppercase' }}>
            {d.date} · Issue {d.issueNumber}
          </div>
        </div>
      </div>

      {/* Body */}
      <div style={{ padding: '28px 32px', display: 'flex', flexDirection: 'column', gap: 32 }}>

        {/* Section 1 · Day in Review */}
        <div>
          <SectionLabel number="01" title="Day in Review" />
          <p style={{ ...SERIF, fontSize: '1.08rem', color: CREAM, fontWeight: 400, margin: '0 0 16px', lineHeight: 1.5 }}>
            {d.dayInReview.headline}
          </p>
          <div style={{
            background: 'rgba(0,0,0,0.2)',
            border: `1px solid ${DIVIDER}`,
            borderRadius: 4,
            padding: '4px 16px 4px',
            marginBottom: 16,
          }}>
            <div style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              padding: '6px 0 8px',
              borderBottom: `1px solid ${DIVIDER}`,
              marginBottom: 2,
            }}>
              <div style={{ ...LABEL, fontSize: 8, letterSpacing: '0.22em', textTransform: 'uppercase', color: MUTED }}>Instrument</div>
              <div style={{ ...LABEL, fontSize: 8, letterSpacing: '0.22em', textTransform: 'uppercase', color: MUTED, textAlign: 'right' }}>Close</div>
              <div style={{ ...LABEL, fontSize: 8, letterSpacing: '0.22em', textTransform: 'uppercase', color: MUTED, textAlign: 'right' }}>Change</div>
            </div>
            {d.dayInReview.marketSignals.map(s => (
              <MarketSignalRow key={s.label} {...s} />
            ))}
          </div>
          <p style={{ ...BODY, fontSize: '0.8rem', color: 'rgba(250,248,244,0.65)', lineHeight: 1.65, margin: 0 }}>
            {d.dayInReview.pipelineNote}
          </p>
        </div>

        <div style={{ height: 1, background: DIVIDER }} />

        {/* Section 2 · Stalled Deals */}
        <div>
          <SectionLabel number="02" title="Stalled Deals · DOM > 45 Days" />
          <p style={{ ...BODY, fontSize: '0.8rem', color: 'rgba(250,248,244,0.65)', lineHeight: 1.65, margin: '0 0 14px' }}>
            {d.stalledDeals.note}
          </p>
          {d.stalledDeals.deals.map((deal, i) => (
            <div key={i} style={{
              background: 'rgba(192,57,43,0.08)',
              border: '1px solid rgba(192,57,43,0.25)',
              borderRadius: 4,
              padding: '12px 16px',
              marginBottom: 10,
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6 }}>
                <div style={{
                  ...LABEL,
                  fontSize: 8,
                  letterSpacing: '0.2em',
                  textTransform: 'uppercase',
                  color: '#e74c3c',
                  background: 'rgba(192,57,43,0.15)',
                  border: '1px solid rgba(192,57,43,0.3)',
                  borderRadius: 2,
                  padding: '2px 7px',
                }}>
                  DOM {deal.dom}
                </div>
                <div style={{ ...BODY, fontSize: '0.82rem', color: CREAM, fontWeight: 600 }}>{deal.address}</div>
                <div style={{ ...BODY, fontSize: '0.75rem', color: MUTED, marginLeft: 'auto' }}>{deal.town} · {deal.price}</div>
              </div>
              <div style={{ ...BODY, fontSize: '0.76rem', color: 'rgba(250,248,244,0.6)', lineHeight: 1.5 }}>
                {deal.action}
              </div>
            </div>
          ))}
          <div style={{
            background: 'rgba(200,172,120,0.06)',
            border: `1px solid ${DIVIDER}`,
            borderRadius: 4,
            padding: '10px 14px',
          }}>
            <div style={{ ...BODY, fontSize: '0.76rem', color: 'rgba(250,248,244,0.55)', lineHeight: 1.6, fontStyle: 'italic' }}>
              {d.stalledDeals.instruction}
            </div>
          </div>
        </div>

        <div style={{ height: 1, background: DIVIDER }} />

        {/* Section 3 · Tomorrow Edge */}
        <div>
          <SectionLabel number="03" title="Tomorrow Edge" />
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {[
              { label: 'First Priority', value: d.tomorrowEdge.firstPriority, icon: '\u25b2' },
              { label: 'First Call', value: d.tomorrowEdge.firstCall, icon: '\u25ce' },
              { label: 'First Move', value: d.tomorrowEdge.firstMove, icon: '\u2192' },
            ].map(item => (
              <div key={item.label} style={{
                display: 'flex',
                gap: 14,
                alignItems: 'flex-start',
                background: 'rgba(200,172,120,0.05)',
                border: `1px solid ${DIVIDER}`,
                borderRadius: 4,
                padding: '12px 16px',
              }}>
                <div style={{ ...LABEL, fontSize: 14, color: GOLD, marginTop: 1, minWidth: 16 }}>{item.icon}</div>
                <div>
                  <div style={{ ...LABEL, fontSize: 9, letterSpacing: '0.2em', textTransform: 'uppercase', color: MUTED, marginBottom: 4 }}>
                    {item.label}
                  </div>
                  <div style={{ ...BODY, fontSize: '0.8rem', color: CREAM, lineHeight: 1.6 }}>
                    {item.value}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div style={{ height: 1, background: DIVIDER }} />

        {/* Section 4 · Scripture for Rest */}
        <div>
          <SectionLabel number="04" title={`Scripture for Rest · ${d.scripture.version}`} />
          <div style={{
            background: 'rgba(200,172,120,0.05)',
            borderLeft: `3px solid ${GOLD}`,
            padding: '16px 20px',
            borderRadius: '0 4px 4px 0',
          }}>
            <div style={{ ...SERIF, fontSize: '1.18rem', color: CREAM, fontWeight: 400, lineHeight: 1.6, marginBottom: 10, fontStyle: 'italic' }}>
              "{d.scripture.text}"
            </div>
            <div style={{ ...LABEL, fontSize: 9, letterSpacing: '0.2em', textTransform: 'uppercase', color: GOLD }}>
              {d.scripture.reference} · {d.scripture.version}
            </div>
          </div>
          <p style={{ ...BODY, fontSize: '0.76rem', color: 'rgba(250,248,244,0.5)', lineHeight: 1.6, margin: '10px 0 0', fontStyle: 'italic' }}>
            {d.scripture.note}
          </p>
        </div>

        <div style={{ height: 1, background: DIVIDER }} />

        {/* Section 5 · Mentor Line */}
        <div>
          <SectionLabel number="05" title="Mentor Line" />
          <div style={{
            background: 'rgba(200,172,120,0.05)',
            border: `1px solid ${DIVIDER}`,
            borderRadius: 4,
            padding: '16px 20px',
          }}>
            <div style={{ ...SERIF, fontSize: '1.1rem', color: CREAM, fontWeight: 400, lineHeight: 1.6, marginBottom: 8, fontStyle: 'italic' }}>
              "{d.mentorLine.quote}"
            </div>
            <div style={{ ...LABEL, fontSize: 9, letterSpacing: '0.2em', textTransform: 'uppercase', color: GOLD, marginBottom: 8 }}>
              — {d.mentorLine.attribution}
            </div>
            <div style={{ ...BODY, fontSize: '0.76rem', color: 'rgba(250,248,244,0.5)', lineHeight: 1.6, fontStyle: 'italic' }}>
              {d.mentorLine.context}
            </div>
          </div>
        </div>

        <div style={{ height: 1, background: DIVIDER }} />

        {/* Section 6 · Soli Deo Gloria */}
        <div style={{ textAlign: 'center', padding: '8px 0 4px' }}>
          <SectionLabel number="06" title="Close" />
          <p style={{ ...BODY, fontSize: '0.82rem', color: 'rgba(250,248,244,0.6)', lineHeight: 1.7, margin: '0 0 18px' }}>
            {d.soliDeoGloria.close}
          </p>
          <div style={{
            ...SERIF,
            fontSize: '1.35rem',
            color: GOLD,
            fontWeight: 400,
            letterSpacing: '0.06em',
            fontStyle: 'italic',
          }}>
            {d.soliDeoGloria.benediction}
          </div>
          <div style={{ ...LABEL, fontSize: 8, letterSpacing: '0.22em', textTransform: 'uppercase', color: MUTED, marginTop: 10 }}>
            Christie\'s East Hampton · 26 Park Place · East Hampton, NY 11937
          </div>
        </div>

      </div>
    </div>
  );
}
