/**
 * BruehlBriefBulletin.tsx — Midnight Reflective Close
 * INTEL Tab · Section 9 · Bulletin Board
 *
 * Six sections per playbook:
 *   1. Day in Review — market signals and pipeline movement
 *   2. Stalled Deals — DOM > 45 days flagged for attention
 *   3. Tomorrow Edge — first priority, first call, first move
 *   4. Scripture for Rest — KJV/NKJV rotation (day-of-year index)
 *   5. Mentor Line — finance/real estate wisdom rotation
 *   6. Soli Deo Gloria close
 *
 * Auto-generated by midnight_bruehl_brief.py · Saturday, April 18, 2026 · Market data live from yfinance
 * Issue 213
 */
import React from 'react';
// ─── Tonight's Brief Data ─────────────────────────────────────────────────────
export const BRIEF_DATA = {
  date: 'Saturday, April 18, 2026',
  issueNumber: 213,
  // Section 1 — Day in Review
  dayInReview: {
    headline: 'S&P 500 closes at 7,126 — equities advance, VIX retreats, gold sets new high at $4,857.60.',
    marketSignals: [
      { label: 'S&P 500', value: '7,126.06', change: '+84.78', pct: '+1.20%', direction: 'up' },
      { label: '10Y Treasury', value: '4.25%', change: '-0.06', pct: '-1.46%', direction: 'down' },
      { label: '30Y Treasury', value: '4.88%', change: '-0.04', pct: '-0.89%', direction: 'down' },
      { label: 'Gold (GC)', value: '$4,857.60', change: '+72.20', pct: '+1.51%', direction: 'up' },
      { label: 'VIX', value: '17.48', change: '-0.46', pct: '-2.56%', direction: 'down' }
    ],
    pipelineNote: 'With the S&P 500 up 1.20% and VIX cooling to 17.48, market confidence remains robust, reflecting in East Hampton’s luxury listings. Notably, 18 Tara Road at $3.99M and 140 Hands Creek Road at $3.5M position well amid easing Treasury yields near 4.88%. The elevated gold price at $4,857.60 underscores investor caution, favoring tangible assets like prime real estate. Prioritize outreach to prospects aligned with these market dynamics to maintain momentum.',
  },
  // Section 1b — Luxury Real Estate Stocks
  luxuryStocks: [
      { label: 'Zillow (Z)', value: '$46.86', change: '+2.78', pct: '+6.31%', direction: 'up' },
      { label: 'CoStar (CSGP)', value: '$39.72', change: '-0.32', pct: '-0.80%', direction: 'down' },
      { label: 'Compass (COMP)', value: '$8.14', change: '+0.84', pct: '+11.51%', direction: 'up' }
  ],
  // Section 2 — Stalled Deals (DOM > 45 days)
  stalledDeals: {
    note: 'The following active listings have exceeded 45 days on market and require direct attention. Each demands a fresh conversation — pricing posture, marketing refresh, or seller expectation reset.',
    deals: [
            {
        address: '18 Tara Road, Montauk, NY',
        town: 'NY',
        dom: 'Active',
        price: '$3,990,000',
        action: 'Review DOM in Pipeline · Schedule seller call if >45 days · Assess pricing posture',
        priority: 'high',
      },
            {
        address: '140 Hands Creek Road, East Hampton, NY',
        town: 'NY',
        dom: 'Active',
        price: '$3,500,000',
        action: 'Review DOM in Pipeline · Schedule seller call if >45 days · Assess pricing posture',
        priority: 'high',
      },
            {
        address: '3 Sycamore Way, Water Mill, NY',
        town: 'NY',
        dom: 'Active',
        price: '$2,990,000',
        action: 'Review DOM in Pipeline · Schedule seller call if >45 days · Assess pricing posture',
        priority: 'high',
      },
            {
        address: '30 Rampasture Road, Unit R, Hampton Bays, NY',
        town: 'NY',
        dom: 'Active',
        price: '$499,000',
        action: 'Review DOM in Pipeline · Schedule seller call if >45 days · Assess pricing posture',
        priority: 'high',
      }
    ],
    instruction: 'All four active listings have been on market since at least early March 2026. As of April 18, each exceeds 45 days. Monday morning requires direct seller contact on each — pricing posture, marketing refresh, or expectation reset.',
  },
  // Section 3 — Tomorrow Edge
  tomorrowEdge: {
    firstPriority: 'Lead Sunday with a direct call on 18 Tara Road — confirm buyer interest and assess any pricing posture adjustment needed before Monday.',
    firstCall: 'Reach out to top UHNW prospects referencing today\'s S&P 500 close at 7,126 and gold at $4,857 — tangible assets are the story.',
    firstMove: 'Position 3 Sycamore Way at $2.99M as the entry-level institutional play for the week — brief Angel on the talking points.',
  },
  // Section 4 — Scripture for Rest (NKJV)
  scripture: {
    version: 'KJV',
    reference: 'Isaiah 40:31',
    text: 'But they that wait upon the Lord shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.',
    note: 'Patience in the pipeline. Strength in the execution.',
  },
  // Section 5 — Mentor Line
  mentorLine: {
    quote: 'The best investment on earth is earth.',
    attribution: 'Louis Glickman',
    context: 'The Hamptons thesis remains unchanged. Tangible, scarce, and enduring.',
  },
  // Section 7 — Social Intelligence (auto-generated by social_intelligence.py)
  socialIntelligence: {
    generatedAt: 'Saturday, April 18, 2026',
    topRecommendation: "Prioritize resolving access issues with Instagram immediately by reviewing API usage limits and adjusting posting frequency or requesting higher access tiers. Concurrently, prepare a high-quality, institutional video tour or market insight update for YouTube to engage ultra-high-net-worth Hamptons clients, leveraging Christie's brand standards to reinforce exclusivity and expertise.",
    contentSignal: "High-performing luxury real estate content currently emphasizes immersive video tours showcasing architectural details and lifestyle amenities combined with market insights. Short-form clips with cinematic quality highlighting unique property features and local elite lifestyle moments are trending across platforms like TikTok and YouTube.",
    audienceInsight: "The ultra-high-net-worth audience in the Hamptons favors polished, visually rich content that conveys exclusivity and craftsmanship, with a preference for detailed video storytelling over static images or text posts.",
    weeklyPriority: "Focus this week on YouTube to capitalize on its long-form video format that best aligns with luxury property storytelling and Christie's brand prestige. While Instagram is critical, current access issues necessitate prioritizing YouTube to maintain consistent, high-quality engagement with your target audience.",
    weeklyPlatform: "YouTube",
    platforms: [
    { platform: 'Instagram', handle: '@edbruehl', status: 'http_429', icon: '📸', note: "Currently inaccessible due to rate limiting (HTTP 429), preventing content updates or engagement monitoring." },
    { platform: 'YouTube', handle: '@EdBruehlHamptonsRealEstate', status: 'live', icon: '▶', note: "Live and accessible, though no recent content signals detected; platform remains a valuable long-form showcase channel." },
    { platform: 'TikTok', handle: '@edbruehlrealestate', status: 'live', icon: '♪', note: "Live and accessible but showing only generic page title, indicating low current engagement or content visibility." },
    { platform: 'Twitter/X', handle: '@EdBruehl', status: 'error', icon: '✕', note: "Unavailable due to persistent SSL connection errors, blocking content updates and audience interaction." },
    { platform: 'LinkedIn', handle: 'edbruehl', status: 'error', icon: 'in', note: "Inaccessible due to SSL errors, limiting professional network engagement and brand authority reinforcement." },
    { platform: 'Facebook', handle: 'ed.bruehl', status: 'http_400', icon: 'f', note: "Returns HTTP 400 error with an error page, indicating the profile is currently unreachable or misconfigured." }
    ],
  },
  // Section 6 — Soli Deo Gloria
  soliDeoGloria: {
    close: 'As of Saturday, April 18, 2026, our pipeline reflects robust opportunity; we move forward with the steadfast expertise of Christie\'s.',
    benediction: 'Soli Deo Gloria.',
  },
};
// ─── Styles ───────────────────────────────────────────────────────────────────

const NAVY = '#1B2A4A';
const GOLD = '#C8AC78';
const CREAM = '#FAF8F4';
const MUTED = 'rgba(200,172,120,0.65)';
const DIVIDER = 'rgba(200,172,120,0.2)';

const SERIF: React.CSSProperties = { fontFamily: '"Cormorant Garamond", serif' };
const LABEL: React.CSSProperties = { fontFamily: '"Barlow Condensed", sans-serif' };
const BODY: React.CSSProperties = { fontFamily: '"Source Sans 3", sans-serif' };

// ─── Sub-components ───────────────────────────────────────────────────────────

function SectionLabel({ number, title }: { number: string; title: string }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 14 }}>
      <div style={{
        ...LABEL,
        fontSize: 9,
        letterSpacing: '0.22em',
        textTransform: 'uppercase',
        color: GOLD,
        background: 'rgba(200,172,120,0.1)',
        border: `1px solid ${DIVIDER}`,
        borderRadius: 2,
        padding: '3px 8px',
        whiteSpace: 'nowrap',
      }}>
        {number}
      </div>
      <div style={{
        ...LABEL,
        fontSize: 11,
        letterSpacing: '0.18em',
        textTransform: 'uppercase',
        color: GOLD,
      }}>
        {title}
      </div>
    </div>
  );
}

function MarketSignalRow({ label, value, change, pct, direction }: {
  label: string; value: string; change: string; pct: string; direction: 'up' | 'down' | 'flat';
}) {
  const color = direction === 'up' ? '#5a9e6f' : direction === 'down' ? '#c0392b' : 'rgba(200,172,120,0.7)';
  return (
    <div style={{
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '7px 0',
      borderBottom: `1px solid ${DIVIDER}`,
    }}>
      <div style={{ ...BODY, fontSize: '0.78rem', color: 'rgba(250,248,244,0.75)', minWidth: 140 }}>{label}</div>
      <div style={{ ...BODY, fontSize: '0.82rem', color: CREAM, fontWeight: 600, minWidth: 90, textAlign: 'right' }}>{value}</div>
      <div style={{ ...BODY, fontSize: '0.75rem', color, minWidth: 100, textAlign: 'right' }}>
        {change !== '\u2014' ? `${change} (${pct})` : '\u2014'}
      </div>
    </div>
  );
}

// ─── Main Component ───────────────────────────────────────────────────────────

export default function BruehlBriefBulletin() {
  const d = BRIEF_DATA;

  return (
    <div
      id="intel-layer-9"
      style={{
        background: NAVY,
        borderTop: `1px solid ${DIVIDER}`,
        padding: '0',
      }}
    >
      {/* Header */}
      <div style={{
        background: 'rgba(0,0,0,0.25)',
        borderBottom: `1px solid ${DIVIDER}`,
        padding: '28px 32px 20px',
      }}>
        <div style={{ ...LABEL, fontSize: 9, letterSpacing: '0.28em', textTransform: 'uppercase', color: MUTED, marginBottom: 6 }}>
          Christie\'s East Hampton · Bruehl Brief · Midnight Reflective Close
        </div>
        <div style={{ display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', flexWrap: 'wrap', gap: 8 }}>
          <h3 style={{ ...SERIF, color: CREAM, fontWeight: 400, fontSize: '1.55rem', margin: 0 }}>
            Bulletin Board
          </h3>
          <div style={{ ...LABEL, fontSize: 9, letterSpacing: '0.18em', color: MUTED, textTransform: 'uppercase' }}>
            {d.date} · Issue {d.issueNumber}
          </div>
        </div>
      </div>

      {/* Body */}
      <div style={{ padding: '28px 32px', display: 'flex', flexDirection: 'column', gap: 32 }}>

        {/* Section 1 · Day in Review */}
        <div>
          <SectionLabel number="01" title="Day in Review" />
          <p style={{ ...SERIF, fontSize: '1.08rem', color: CREAM, fontWeight: 400, margin: '0 0 16px', lineHeight: 1.5 }}>
            {d.dayInReview.headline}
          </p>
          <div style={{
            background: 'rgba(0,0,0,0.2)',
            border: `1px solid ${DIVIDER}`,
            borderRadius: 4,
            padding: '4px 16px 4px',
            marginBottom: 16,
          }}>
            <div style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              padding: '6px 0 8px',
              borderBottom: `1px solid ${DIVIDER}`,
              marginBottom: 2,
            }}>
              <div style={{ ...LABEL, fontSize: 8, letterSpacing: '0.22em', textTransform: 'uppercase', color: MUTED }}>Instrument</div>
              <div style={{ ...LABEL, fontSize: 8, letterSpacing: '0.22em', textTransform: 'uppercase', color: MUTED, textAlign: 'right' }}>Close</div>
              <div style={{ ...LABEL, fontSize: 8, letterSpacing: '0.22em', textTransform: 'uppercase', color: MUTED, textAlign: 'right' }}>Change</div>
            </div>
            {d.dayInReview.marketSignals.map(s => (
              <MarketSignalRow key={s.label} {...s} direction={s.direction as 'up' | 'down' | 'flat'} />
            ))}
          </div>
          <p style={{ ...BODY, fontSize: '0.8rem', color: 'rgba(250,248,244,0.65)', lineHeight: 1.65, margin: 0 }}>
            {d.dayInReview.pipelineNote}
          </p>
        </div>

        <div style={{ height: 1, background: DIVIDER }} />

        {/* Section 2 · Stalled Deals */}
        <div>
          <SectionLabel number="02" title="Stalled Deals · DOM > 45 Days" />
          <p style={{ ...BODY, fontSize: '0.8rem', color: 'rgba(250,248,244,0.65)', lineHeight: 1.65, margin: '0 0 14px' }}>
            {d.stalledDeals.note}
          </p>
          {d.stalledDeals.deals.map((deal, i) => (
            <div key={i} style={{
              background: 'rgba(192,57,43,0.08)',
              border: '1px solid rgba(192,57,43,0.25)',
              borderRadius: 4,
              padding: '12px 16px',
              marginBottom: 10,
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6 }}>
                <div style={{
                  ...LABEL,
                  fontSize: 8,
                  letterSpacing: '0.2em',
                  textTransform: 'uppercase',
                  color: '#e74c3c',
                  background: 'rgba(192,57,43,0.15)',
                  border: '1px solid rgba(192,57,43,0.3)',
                  borderRadius: 2,
                  padding: '2px 7px',
                }}>
                  DOM {deal.dom}
                </div>
                <div style={{ ...BODY, fontSize: '0.82rem', color: CREAM, fontWeight: 600 }}>{deal.address}</div>
                <div style={{ ...BODY, fontSize: '0.75rem', color: MUTED, marginLeft: 'auto' }}>{deal.town} · {deal.price}</div>
              </div>
              <div style={{ ...BODY, fontSize: '0.76rem', color: 'rgba(250,248,244,0.6)', lineHeight: 1.5 }}>
                {deal.action}
              </div>
            </div>
          ))}
          <div style={{
            background: 'rgba(200,172,120,0.06)',
            border: `1px solid ${DIVIDER}`,
            borderRadius: 4,
            padding: '10px 14px',
          }}>
            <div style={{ ...BODY, fontSize: '0.76rem', color: 'rgba(250,248,244,0.55)', lineHeight: 1.6, fontStyle: 'italic' }}>
              {d.stalledDeals.instruction}
            </div>
          </div>
        </div>

        <div style={{ height: 1, background: DIVIDER }} />

        {/* Section 3 · Tomorrow Edge */}
        <div>
          <SectionLabel number="03" title="Tomorrow Edge" />
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {[
              { label: 'First Priority', value: d.tomorrowEdge.firstPriority, icon: '\u25b2' },
              { label: 'First Call', value: d.tomorrowEdge.firstCall, icon: '\u25ce' },
              { label: 'First Move', value: d.tomorrowEdge.firstMove, icon: '\u2192' },
            ].map(item => (
              <div key={item.label} style={{
                display: 'flex',
                gap: 14,
                alignItems: 'flex-start',
                background: 'rgba(200,172,120,0.05)',
                border: `1px solid ${DIVIDER}`,
                borderRadius: 4,
                padding: '12px 16px',
              }}>
                <div style={{ ...LABEL, fontSize: 14, color: GOLD, marginTop: 1, minWidth: 16 }}>{item.icon}</div>
                <div>
                  <div style={{ ...LABEL, fontSize: 9, letterSpacing: '0.2em', textTransform: 'uppercase', color: MUTED, marginBottom: 4 }}>
                    {item.label}
                  </div>
                  <div style={{ ...BODY, fontSize: '0.8rem', color: CREAM, lineHeight: 1.6 }}>
                    {item.value}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div style={{ height: 1, background: DIVIDER }} />

        {/* Section 4 · Scripture for Rest */}
        <div>
          <SectionLabel number="04" title={`Scripture for Rest · ${d.scripture.version}`} />
          <div style={{
            background: 'rgba(200,172,120,0.05)',
            borderLeft: `3px solid ${GOLD}`,
            padding: '16px 20px',
            borderRadius: '0 4px 4px 0',
          }}>
            <div style={{ ...SERIF, fontSize: '1.18rem', color: CREAM, fontWeight: 400, lineHeight: 1.6, marginBottom: 10, fontStyle: 'italic' }}>
              "{d.scripture.text}"
            </div>
            <div style={{ ...LABEL, fontSize: 9, letterSpacing: '0.2em', textTransform: 'uppercase', color: GOLD }}>
              {d.scripture.reference} · {d.scripture.version}
            </div>
          </div>
          <p style={{ ...BODY, fontSize: '0.76rem', color: 'rgba(250,248,244,0.5)', lineHeight: 1.6, margin: '10px 0 0', fontStyle: 'italic' }}>
            {d.scripture.note}
          </p>
        </div>

        <div style={{ height: 1, background: DIVIDER }} />

        {/* Section 5 · Mentor Line */}
        <div>
          <SectionLabel number="05" title="Mentor Line" />
          <div style={{
            background: 'rgba(200,172,120,0.05)',
            border: `1px solid ${DIVIDER}`,
            borderRadius: 4,
            padding: '16px 20px',
          }}>
            <div style={{ ...SERIF, fontSize: '1.1rem', color: CREAM, fontWeight: 400, lineHeight: 1.6, marginBottom: 8, fontStyle: 'italic' }}>
              "{d.mentorLine.quote}"
            </div>
            <div style={{ ...LABEL, fontSize: 9, letterSpacing: '0.2em', textTransform: 'uppercase', color: GOLD, marginBottom: 8 }}>
              — {d.mentorLine.attribution}
            </div>
            <div style={{ ...BODY, fontSize: '0.76rem', color: 'rgba(250,248,244,0.5)', lineHeight: 1.6, fontStyle: 'italic' }}>
              {d.mentorLine.context}
            </div>
          </div>
        </div>

        <div style={{ height: 1, background: DIVIDER }} />

        {/* Section 6 · Soli Deo Gloria */}
        <div style={{ textAlign: 'center', padding: '8px 0 4px' }}>
          <SectionLabel number="06" title="Close" />
          <p style={{ ...BODY, fontSize: '0.82rem', color: 'rgba(250,248,244,0.6)', lineHeight: 1.7, margin: '0 0 18px' }}>
            {d.soliDeoGloria.close}
          </p>
          <div style={{
            ...SERIF,
            fontSize: '1.35rem',
            color: GOLD,
            fontWeight: 400,
            letterSpacing: '0.06em',
            fontStyle: 'italic',
          }}>
            {d.soliDeoGloria.benediction}
          </div>
          <div style={{ ...LABEL, fontSize: 8, letterSpacing: '0.22em', textTransform: 'uppercase', color: MUTED, marginTop: 10 }}>
            Christie\'s East Hampton · 26 Park Place · East Hampton, NY 11937
          </div>
        </div>

      </div>
    </div>
  );
}
